<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-27T18:38:51 IST" name="Suite" finished-at="2024-06-27T18:39:06 IST" duration-ms="14895">
    <groups>
      <group name="Error">
        <method signature="ErrorValidations.submitOrder()[pri:0, instance:Selenium.Framework.ErrorValidations@1941a8ff]" name="submitOrder" class="Selenium.Framework.ErrorValidations"/>
      </group> <!-- Error -->
    </groups>
    <test started-at="2024-06-27T18:38:51 IST" name="Test" finished-at="2024-06-27T18:39:02 IST" duration-ms="10841">
      <class name="Selenium.Framework.standalone">
        <test-method is-config="true" signature="launch()[pri:0, instance:Selenium.Framework.standalone@29a0cdb]" started-at="2024-06-27T18:38:51 IST" name="launch" finished-at="2024-06-27T18:38:57 IST" duration-ms="5221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Selenium.Framework.standalone@29a0cdb]" started-at="2024-06-27T18:38:57 IST" name="submitOrder" data-provider="data" finished-at="2024-06-27T18:39:02 IST" duration-ms="5434" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=@Keshav1999, product=ZARA COAT 3, email=mwadhwa2706@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- Selenium.Framework.standalone -->
    </test> <!-- Test -->
    <test started-at="2024-06-27T18:39:02 IST" name="Error Validations" finished-at="2024-06-27T18:39:06 IST" duration-ms="3754">
      <class name="Selenium.Framework.ErrorValidations">
        <test-method is-config="true" signature="launch()[pri:0, instance:Selenium.Framework.ErrorValidations@1941a8ff]" started-at="2024-06-27T18:39:02 IST" name="launch" finished-at="2024-06-27T18:39:05 IST" duration-ms="2826" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="submitOrder()[pri:0, instance:Selenium.Framework.ErrorValidations@1941a8ff]" started-at="2024-06-27T18:39:05 IST" name="submitOrder" finished-at="2024-06-27T18:39:05 IST" duration-ms="407" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Selenium.Framework.ErrorValidations.submitOrder(ErrorValidations.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- Selenium.Framework.ErrorValidations -->
    </test> <!-- Error Validations -->
  </suite> <!-- Suite -->
</testng-results>
